# Generated by Django 5.0.4 on 2024-04-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_attendance_created_at_attendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created_at']},
        ),
    ]
