# Generated by Django 5.0.4 on 2024-04-28 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_attendance_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
