# Generated by Django 5.0.4 on 2024-05-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_leave_description_alter_leave_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('question', 'classroom')},
        ),
    ]
