# Generated by Django 5.0.4 on 2024-05-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_assessment_unique_together'),
        ('student', '0005_assessmentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentanswer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentanswer',
            unique_together={('assessment', 'student')},
        ),
    ]
